; Healing_Stats Malay UI strings.
; Translate from localization/canonical/Healing_Stats.en.ini.

[default_windows]
0_name=Jumlah
0_title_format=Jumlah ({1}s tempur)
0_entry_format={1} ({4}/s)
1_name=Sasaran
1_title_format=Sasaran {1} ({4}/s, {7}s tempur)
2_name=Skill
2_title_format=Skill {1} ({4}/s, {7}s tempur)
3_name=Sasaran (tick)
3_title_format=Sasaran {1} ({5}/tick, {2} tick)
3_entry_format={1} ({5}/tick, {2} tick)
3_details_entry_format={1} ({5}/tick, {2} tick)
4_name=Skill (tick)
4_title_format=Skill {1} ({5}/tick, {2} tick)
4_entry_format={1} ({5}/tick, {2} tick)
4_details_entry_format={1} ({5}/tick, {2} tick)
5_name=Stat ahli skuad
5_title_format=Heal keluar {1} ({4}/s, {7}s tempur)
6_name=Barrier ahli skuad
6_title_format=Jana barrier {1} ({4}/s, {7}s tempur)
9_name=Gabungan
9_title_format=Gabungan {1} ({4}/s, {7}s tempur)

[enum_auto_update]
off=mati
stable=hidup (stable sahaja)
prerelease=hidup (prerelease/stable)

[enum_data_source]
targets=sasaran
skills=skill
totals=jumlah
combined=gabungan
peers_outgoing=stat ahli skuad

[enum_sort_order]
alphabetical_ascending=abjad menaik
alphabetical_descending=abjad menurun
total_outgoing_per_second_ascending=jumlah keluar per saat menaik
total_outgoing_per_second_descending=jumlah keluar per saat menurun
heal_per_second_ascending=heal per saat menaik
heal_per_second_descending=heal per saat menurun
barrier_generation_per_second_ascending=jana barrier per saat menaik
barrier_generation_per_second_descending=jana barrier per saat menurun

[enum_combat_end]
combat_exit=keluar combat
last_damage_event=event damage terakhir
last_heal_event=event heal terakhir
last_damage_or_heal_event=event damage / heal terakhir

[enum_position]
manual=manual
screen_relative=relatif skrin
window_relative=relatif window

[enum_corner_position]
top_left=atas-kiri
top_right=atas-kanan
bottom_left=bawah-kiri
bottom_right=bawah-kanan

[group_filter]
group=Kumpulan
squad=Skuad
all_excluding_summons=Semua (kecuali summon)
all_including_summons=Semua (termasuk summon)

[aggregates]
from_damage_dealt=Daripada damage diberi

[messages]
live_stats_disabled_peers=Perkongsian stat langsung dilumpuhkan. Aktifkan "perkongsian stat langsung" di bawah "Pilihan Heal Stats" untuk melihat heal yang dibuat oleh pemain lain dalam skuad.
live_stats_not_connected=Tidak bersambung ke server perkongsian stat langsung ("%s").

[details]
total_healing=jumlah heal
total_barrier_generation=jumlah barrier
hits=tick
casts=cast
healing_per_second=heal per saat
healing_per_hit=heal per tick
healing_per_cast=heal per cast
barrier_generation_per_second=jana barrier per saat
barrier_generation_per_hit=jana barrier per tick
barrier_generation_per_cast=jana barrier per cast

[position]
relative_to_corner=relatif kepada sudut
from_anchor_panel_corner=dari sudut panel anchor
to_this_panel_corner=ke sudut panel ini
anchor_window=window anchor

[combined_headers]
totals=Jumlah
targets=Sasaran
skills=Skill

[rpc_status]
with_encryption=dengan
without_encryption=tanpa
connected=Bersambung ke %s selama %llu saat %s penyulitan
disabled=Tidak bersambung kerana perkongsian stat langsung dilumpuhkan
failed=Gagal bersambung ke %s. Mencuba lagi...

[window_options]
details_entry_format=format entri
data_source=sumber data
sort_order=susunan
stats_exclude=stat dikecualikan
exclude_group=kumpulan
exclude_off_group=luar kumpulan
exclude_off_squad=luar skuad
exclude_summons=summon
exclude_unmapped=tidak dipetakan
exclude_healing=heal
exclude_barrier_generation=jana barrier
combat_end=akhir combat
display=Paparan
draw_bars=lukis bar
use_subgroup_for_bar_colour=warna bar ikut subgroup
use_profession_for_bar_colour=warna bar ikut profession
index_numbers=nombor indeks
profession_text=teks profession
profession_icons=ikon profession
replace_player_with_account_name=ganti pemain dengan nama akaun
use_profession_for_name_colour=warna nama ikut profession
use_subgroup_for_name_colour=warna nama ikut subgroup
self_on_top=diri di atas
hide_self_from_list=sembunyi diri dari senarai
self_only=diri sahaja
anonymous_mode=mod anonim
short_name=nama pendek
max_name_length=had panjang nama
min_displayed=min dipapar
max_displayed=maks dipapar
stats_format=format stat
title_bar_format=format bar tajuk
style=Gaya
title_bar=bar tajuk
scroll_bar=bar skrol
background=latar
auto_resize_window=auto saiz window
window_width=lebar window
position=Posisi
hotkey=Hotkey

[addon_options]
title=Heal Stats
custom_window=window tersuai
auto_updates=auto update
debug_mode=mod debug
debug_logging=log debug
log_healing_to_evtc_logs=log heal ke log EVTC
enable_live_stats_sharing=aktifkan perkongsian stat langsung
live_stats_budget_mode=perkongsian stat langsung - mod jimat
live_stats_disable_encryption=perkongsian stat langsung - lumpuhkan penyulitan
sharing_hotkey=Hotkey perkongsian
evtc_rpc_server=EVTC RPC server
reset_options=Reset pilihan

[tooltips]
details_entry_format=Format untuk data dipapar (statistik per entri).\n{1}: Heal\n{2}: Tick\n{3}: Cast (belum dilaksanakan)\n{4}: Heal per saat\n{5}: Heal per tick\n{6}: Heal per cast (belum dilaksanakan)\n{7}: Peratus jumlah heal\n
data_source=Menentukan data yang ditunjukkan dalam window
sort_order=Menentukan cara sasaran dan skill disusun dalam bahagian 'Sasaran' dan 'Skill'.
combat_end=Menentukan apa yang digunakan untuk menentukan akhir\ncombat (dan seterusnya masa dalam combat)
draw_bars=Tunjuk bar berwarna di bawah setiap entri untuk menunjukkan nilai\nentri itu berbanding entri terbesar
short_name=Nama yang digunakan untuk mewakili window ini dalam menu "heal stats"
max_name_length=Potong nama dipapar kepada bilangan aksara ini. Tetapkan 0 untuk lumpuh, -1 untuk sembunyi
min_displayed=Jumlah minimum baris data untuk ditunjukkan dalam window ini.
max_displayed=Jumlah maksimum baris data untuk ditunjukkan dalam window ini. Tetapkan 0 tanpa had
stats_format_with_percent=Format untuk data dipapar (statistik per entri).\n{1}: Heal\n{2}: Tick\n{3}: Cast (belum dilaksanakan)\n{4}: Heal per saat\n{5}: Heal per tick\n{6}: Heal per cast (belum dilaksanakan)\n{7}: Peratus jumlah heal
stats_format=Format untuk data dipapar (statistik per entri).\n{1}: Heal\n{2}: Tick\n{3}: Cast (belum dilaksanakan)\n{4}: Heal per saat\n{5}: Heal per tick\n{6}: Heal per cast (belum dilaksanakan)
title_bar_format=Format untuk tajuk window ini.\n{1}: Jumlah heal\n{2}: Jumlah tick\n{3}: Jumlah cast (belum dilaksanakan)\n{4}: Heal per saat\n{5}: Heal per tick\n{6}: Heal per cast (belum dilaksanakan)\n{7}: Masa dalam combat
title_bar_format_totals=Format untuk tajuk window ini.\n{1}: Masa dalam combat
window_width=Tetapkan 0 untuk ubah saiz lebar secara dinamik
window_hotkey=Nilai angka (kod kekunci maya) untuk kekunci\nyang digunakan membuka dan menutup window ini
debug_mode=Memasukkan data debug dalam nama sasaran dan skill.\nHidupkan sebelum mengambil screenshot isu kiraan yang mungkin berlaku.
debug_logging=Jika tidak ditetapkan kepada off, aktifkan logging pada tahap log yang dipilih.\nLog disimpan di addons\\logs\\arcdps_healing_stats\\. Logging\nakan memberi kesan kecil pada prestasi.
enable_live_stats_sharing=Mengaktifkan perkongsian langsung statistik heal dengan pemain lain\ndalam skuad anda. Ini dilakukan melalui server pusat\n(lihat pilihan di bawah). Selepas diaktifkan, ia mungkin tidak\nberfungsi betul sehingga instance peta ditukar supaya semua ahli\nskuad dikesan dengan betul.\n\nStat daripada pemain lain boleh dilihat melalui\nwindow heal stats dengan sumber data ditetapkan kepada "%s"\n\nMengaktifkan pilihan ini memberi kesan kecil pada prestasi dan\nmenambah sedikit beban pada sambungan anda (maksimum\nkira-kira 10 kiB/s naik dan 100 kiB/s turun). Penggunaan\nsambungan muat turun meningkat apabila lebih ramai pemain dalam skuad\nmengaktifkan perkongsian stat langsung; penggunaan muat naik\ntidak meningkat.
live_stats_budget_mode=Hantar subset event minimum sahaja kepada peer. Ini mengurangkan\njumlah bandwidth muat naik yang digunakan addon. Statistik heal\nyang dipapar masih tepat, tetapi masa dalam combat boleh\nsedikit salah apabila dilihat oleh peer semasa combat. Jika peer\nmenggunakan versi addon sebelum sokongan pilihan ini,\nmasa dalam combat boleh menjadi jauh salah walaupun\nselepas encounter tamat. Pilihan ini tidak mengurangkan penggunaan\nbandwidth muat turun, hanya bandwidth muat naik. Dengan pilihan ini\ndiaktifkan, penggunaan muat naik dijangka <1kiB/s.
live_stats_disable_encryption=Secara lalai, semua mesej ke dan dari server perkongsian stat langsung\ndisulitkan menggunakan TLS. Pilihan ini melumpuhkan penyulitan. Ini\nmungkin berguna untuk mengelakkan konflik dengan perisian keselamatan,\natau mengurangkan penggunaan CPU perkongsian stat langsung.
sharing_hotkey=Nilai angka (kod kekunci maya) untuk kekunci\nyang digunakan menogol perkongsian stat langsung hidup/mati
evtc_rpc_server=Server untuk komunikasi evtc_rpc\n(membolehkan pemain lain dalam skuad melihat stat heal anda).\nSemua event combat setempat akan dihantar ke server ini,\njadi pastikan server itu dipercayai.
reset_options=Reset semua pilihan global dan pilihan khusus window kepada lalai.

[update]
window_title=Update Healing Stats###HEALING_STATS_UPDATE
available=Update baharu untuk addon healing stats tersedia
current_version=Versi semasa: %u.%urc%u
new_version=Versi baharu: %u.%urc%u
open_download_page=Buka halaman muat turun
update_automatically=Update automatik
update_in_progress=Update sedang berjalan
update_successful=Update selesai, mulakan semula Guild Wars 2 untuk digunakan
update_error=Ralat berlaku semasa update
